# Generated by Django 3.1 on 2021-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_newarrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
