# Generated by Django 3.1 on 2021-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='photos/cover')),
                ('ad_name', models.CharField(blank=True, max_length=50)),
                ('ad_text', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
