# Generated by Django 3.1 on 2021-05-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='cover_image',
            new_name='image',
        ),
    ]
