# Generated by Django 3.1 on 2021-05-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210529_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('razmer', 'razmer'), ('svet', 'svet')], max_length=100),
        ),
    ]
