# Generated by Django 3.1 on 2021-06-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210531_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Телефон номер')),
            ],
        ),
    ]
