# Generated by Django 3.1 on 2021-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Телефон номер'),
        ),
    ]
