# Generated by Django 3.1 on 2021-06-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210606_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_fee',
        ),
    ]
