# Generated by Django 3.1 on 2021-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210607_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Elsom', 'Elsom'), ('Bank', 'Bank')], default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
