# Generated by Django 3.1 on 2021-06-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210614_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
